/**
 * Setup script to create .env file for Petro-Core frontend
 * Run with: node setup-env.js
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

// Get the directory name
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Configuration values from existing setup-supabase.js
const SUPABASE_URL = 'https://tobjghstopxuntbewrxu.supabase.co';
const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRvYmpnaHN0b3B4dW50YmV3cnh1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTcyMDU1MDcsImV4cCI6MjAzMjc4MTUwN30.fOZFqrPtOkE4q6X9X6isgGpC8RO7XgXjpj9jOHQBQYI';

// .env file content
const envContent = `# Supabase Configuration
VITE_SUPABASE_URL=${SUPABASE_URL}
VITE_SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}

# API Configuration  
VITE_local_url=http://localhost:8001
VITE_API_URL=https://petro-core-usep-iw23.onrender.com/api

# This file was auto-generated by setup-env.js
# Generated on: ${new Date().toISOString()}
`;

// Path to .env file
const envFilePath = path.join(__dirname, '.env');

try {
  // Check if .env already exists
  if (fs.existsSync(envFilePath)) {
    console.log('⚠️  .env file already exists. Backing up existing file...');
    const backupPath = path.join(__dirname, `.env.backup.${Date.now()}`);
    fs.copyFileSync(envFilePath, backupPath);
    console.log(`✅ Existing .env backed up to: ${backupPath}`);
  }

  // Write .env file
  fs.writeFileSync(envFilePath, envContent);
  console.log('✅ Created .env file successfully!');
  console.log('📁 Location:', envFilePath);
  console.log('');
  console.log('🔧 Environment variables configured:');
  console.log('   - VITE_SUPABASE_URL');
  console.log('   - VITE_SUPABASE_ANON_KEY');
  console.log('   - VITE_local_url');
  console.log('   - VITE_API_URL');
  console.log('');
  console.log('🚀 You can now start the frontend server with: npm run dev');
  console.log('');
  console.log('⚠️  IMPORTANT: If you\'re still having authentication issues after this:');
  console.log('   1. Restart the frontend dev server');
  console.log('   2. Clear browser localStorage (F12 → Application → Local Storage → Clear All)');
  console.log('   3. Log out and log back in');

} catch (error) {
  console.error('❌ Error creating .env file:', error.message);
  process.exit(1);
} 