import { Q_KEYS } from '@/shared/qkeys';
import { useQuery } from '@tanstack/react-query';
import type { IRock, RockCategory } from '../rock.interface';

// Mock function to get rocks - in a real app this would call an API
const getRocks = async (category: string): Promise<IRock[]> => {
  // Simulate API call
  await new Promise(resolve => setTimeout(resolve, 500));
  
  // Mock data with proper categorization
  const mockData: IRock[] = [
    // Igneous Rocks
    {
      id: 'R-0001',
      name: 'Granite',
      type: 'Plutonic',
      depositional_environment: 'Deep crustal',
      grain_size: 'Coarse-grained',
      chemical_formula: 'Complex silicate mixture',
      hardness: '6-7',
      color: 'Pink to gray',
      texture: 'Phaneritic',
      latitude: '45.5122° N',
      longitude: '122.6587° W',
      locality: 'Cascade Range',
      mineral_composition: 'Quartz, K-feldspar, Plagioclase, Biotite',
      category: 'Igneous',
      silica_content: 'Felsic (>65% SiO₂)',
      cooling_rate: 'Slow',
      mineral_content: 'Quartz, K-feldspar, Plagioclase, Biotite, Hornblende',
      status: 'active'
    },
    {
      id: 'R-0002',
      name: 'Basalt',
      type: 'Volcanic',
      depositional_environment: 'Lava flows',
      grain_size: 'Fine-grained',
      chemical_formula: 'Complex silicate mixture',
      hardness: '5-6',
      color: 'Dark gray to black',
      texture: 'Aphanitic',
      category: 'Igneous',
      silica_content: 'Mafic (45-52% SiO₂)',
      cooling_rate: 'Fast',
      mineral_content: 'Pyroxene, Plagioclase, Olivine',
      status: 'active'
    },
    // Sedimentary Rocks
    {
      id: 'R-0003',
      name: 'Limestone',
      type: 'Chemical/Biochemical',
      depositional_environment: 'Marine',
      grain_size: 'Variable',
      chemical_formula: 'CaCO3',
      hardness: '3',
      color: 'White to gray',
      texture: 'Clastic',
      category: 'Sedimentary',
      bedding: 'Massive to thinly bedded',
      sorting: 'Well-sorted',
      roundness: 'N/A (chemical precipitate)',
      fossil_content: 'Shell fragments, marine organisms',
      sediment_source: 'Biogenic - marine shells and skeletons',
      latitude: '10° 32\' 45" N',
      longitude: '123° 55\' 22" E',
      locality: 'Cebu Island, Philippines',
      status: 'active'
    },
    {
      id: 'R-0004',
      name: 'Sandstone',
      type: 'Clastic',
      depositional_environment: 'Beach, river, desert',
      grain_size: 'Medium-grained',
      chemical_formula: 'SiO2',
      hardness: '6-7',
      color: 'Tan to red',
      texture: 'Granular',
      category: 'Sedimentary',
      bedding: 'Cross-bedded',
      sorting: 'Moderately sorted',
      roundness: 'Subrounded to rounded',
      fossil_content: 'Trace fossils',
      sediment_source: 'Terrigenous - from erosion of older rocks',
      latitude: '16° 25\' 18" N',
      longitude: '120° 34\' 27" E',
      locality: 'Baguio, Philippines',
      status: 'active'
    },
    // Metamorphic Rocks
    {
      id: 'M-0001',
      name: 'Marble',
      type: 'Non-foliated',
      depositional_environment: 'Contact or regional metamorphism',
      grain_size: 'Medium to coarse',
      chemical_formula: 'CaCO3',
      hardness: '3-4',
      color: 'White, gray, black, or banded',
      texture: 'Granoblastic',
      category: 'Metamorphic',
      locality: 'Romblon, Philippines',
      latitude: '12° 35\' 42" N',
      longitude: '122° 16\' 30" E',
      mineral_composition: 'Calcite, Dolomite',
      associated_minerals: 'Wollastonite, Diopside, Tremolite',
      metamorphism_type: 'Contact/Regional',
      metamorphic_grade: 'Medium to High',
      parent_rock: 'Limestone',
      foliation: 'No',
      status: 'active'
    },
    {
      id: 'M-0002',
      name: 'Schist',
      type: 'Foliated',
      depositional_environment: 'Regional metamorphism',
      grain_size: 'Medium to coarse',
      chemical_formula: 'Variable',
      hardness: '4-5',
      color: 'Gray to silver, may have red or green hues',
      texture: 'Foliated, schistose',
      category: 'Metamorphic',
      locality: 'Benguet, Philippines',
      latitude: '16° 22\' 08" N',
      longitude: '120° 37\' 19" E',
      mineral_composition: 'Mica, Quartz, Feldspar',
      associated_minerals: 'Biotite, Muscovite, Chlorite, Garnet',
      metamorphism_type: 'Regional',
      metamorphic_grade: 'Medium',
      parent_rock: 'Shale or Mudstone',
      foliation: 'Yes',
      status: 'active'
    },
    {
      id: 'M-0003',
      name: 'Gneiss',
      type: 'Foliated',
      depositional_environment: 'High-grade regional metamorphism',
      grain_size: 'Medium to coarse',
      chemical_formula: 'Variable',
      hardness: '6-7',
      color: 'Banded light and dark minerals',
      texture: 'Gneissic, banded',
      category: 'Metamorphic',
      locality: 'Zambales, Philippines',
      latitude: '15° 08\' 24" N',
      longitude: '120° 05\' 52" E',
      mineral_composition: 'Quartz, Feldspar, Micas, Amphiboles',
      associated_minerals: 'Biotite, Hornblende, Garnet, Sillimanite',
      metamorphism_type: 'Regional',
      metamorphic_grade: 'High',
      parent_rock: 'Granite or Sedimentary Rocks',
      foliation: 'Yes',
      status: 'active'
    },
    {
      id: 'M-0004',
      name: 'Slate',
      type: 'Foliated',
      depositional_environment: 'Low-grade regional metamorphism',
      grain_size: 'Very fine-grained',
      chemical_formula: 'Variable aluminosilicates',
      hardness: '3-4',
      color: 'Gray, black, green, or red',
      texture: 'Slaty cleavage',
      category: 'Metamorphic',
      locality: 'Mountain Province, Philippines',
      latitude: '17° 05\' 36" N',
      longitude: '121° 02\' 42" E',
      mineral_composition: 'Clay minerals, Quartz, Mica',
      associated_minerals: 'Chlorite, Sericite',
      metamorphism_type: 'Regional',
      metamorphic_grade: 'Low',
      parent_rock: 'Shale',
      foliation: 'Yes',
      status: 'active'
    },
    {
      id: 'M-0005',
      name: 'Quartzite',
      type: 'Non-foliated',
      depositional_environment: 'Regional metamorphism',
      grain_size: 'Fine to medium',
      chemical_formula: 'SiO2',
      hardness: '7',
      color: 'White, gray, pink, red',
      texture: 'Granoblastic',
      category: 'Metamorphic',
      locality: 'Ilocos Region, Philippines',
      latitude: '17° 45\' 11" N',
      longitude: '120° 43\' 25" E',
      mineral_composition: 'Quartz',
      associated_minerals: 'Muscovite, Magnetite, Rutile',
      metamorphism_type: 'Regional',
      metamorphic_grade: 'Medium to High',
      parent_rock: 'Sandstone',
      foliation: 'No',
      status: 'active'
    },
    {
      id: 'M-0006',
      name: 'Amphibolite',
      type: 'Foliated',
      depositional_environment: 'Medium to high-grade regional metamorphism',
      grain_size: 'Medium-grained',
      chemical_formula: 'Complex silicates',
      hardness: '5-6',
      color: 'Dark green to black',
      texture: 'Nematoblastic',
      category: 'Metamorphic',
      locality: 'Surigao del Norte, Philippines',
      latitude: '9° 22\' 47" N',
      longitude: '125° 36\' 18" E',
      mineral_composition: 'Hornblende, Plagioclase',
      associated_minerals: 'Garnet, Biotite, Epidote',
      metamorphism_type: 'Regional',
      metamorphic_grade: 'Medium to High',
      parent_rock: 'Basalt or Gabbro',
      foliation: 'Weak to Moderate',
      status: 'active'
    },
    // Ore Samples - from Database.xlsx
    {
      id: 'O-0001',
      name: 'Gold-Copper Ore',
      rock_code: 'O-0001',
      commodity_type: 'Gold-Copper',
      ore_group: 'Hydrothermal (ISE)',
      mining_company: 'Lepanto Consolidated Mining Company',
      type: 'Hydrothermal Ore',
      hardness: '3-4',
      category: 'Ore Samples',
      locality: 'Mankayan, Benguet',
      description: 'Enargite-Luzonite Intergrown with Disseminated Pyrite',
      latitude: '16° 51\' 35" N',
      longitude: '120° 49\' 30" E',
      status: 'active',
      color: 'Gray with metallic luster',
      image_url: '/images/ores/gold-copper-ore.jpg'
    },
    {
      id: 'O-0002',
      name: 'Gold Ore',
      rock_code: 'O-0002',
      commodity_type: 'Gold',
      ore_group: 'Hydrothermal (ISE)',
      mining_company: 'Apex Mining Company, Inc.',
      type: 'Epithermal Ore',
      hardness: '2.5-3',
      category: 'Ore Samples',
      locality: 'Masara, Maco, Davao de Oro',
      description: 'Crustiform-Colloform Banded Quartz + Rhodonite + Rhodochrosite',
      latitude: '7° 22\' 26" N',
      longitude: '126° 6\' 56" E',
      status: 'active',
      color: 'White to pink banded',
      image_url: '/images/ores/gold-ore.jpg'
    },
    {
      id: 'O-0003',
      name: 'Nickel Ore',
      rock_code: 'O-0003',
      commodity_type: 'Nickel',
      ore_group: 'Residual',
      mining_company: 'Taganito Mining Corporation',
      type: 'Lateritic Ore',
      hardness: '2-5',
      category: 'Ore Samples',
      locality: 'Claver, Surigao del Norte',
      description: 'Lateritic Nickel Ore with fractures',
      latitude: '9° 32\' 09" N',
      longitude: '125° 54\' 16" E',
      status: 'active',
      color: 'Reddish-brown to yellow',
      image_url: '/images/ores/nickel-ore.jpg'
    },
    {
      id: 'O-0004',
      name: 'Copper Ore',
      rock_code: 'O-0004',
      commodity_type: 'Copper',
      ore_group: 'Hydrothermal (Porphyry)',
      mining_company: 'Carmen Copper Corporation',
      type: 'Porphyry Ore',
      hardness: '3-4',
      category: 'Ore Samples',
      locality: 'Toledo City, Cebu',
      description: 'Bornite-Chalcopyrite Intergrown with Pyrite',
      latitude: '10° 20\' 8" N',
      longitude: '123° 40\' 14" E',
      status: 'active',
      color: 'Blue-purple tarnish on copper-red',
      image_url: '/images/ores/copper-ore.jpg'
    },
    {
      id: 'O-0005',
      name: 'Iron Ore',
      rock_code: 'O-0005',
      commodity_type: 'Iron',
      ore_group: 'Sedimentary',
      mining_company: 'Philippine Mining Development Corporation',
      type: 'Hematite-Goethite Ore',
      hardness: '5-6',
      category: 'Ore Samples',
      locality: 'Tubay, Agusan Del Norte',
      description: 'Massive Hematite-Goethite with minor Limonite',
      latitude: '9° 10\' 56" N',
      longitude: '125° 31\' 27" E',
      status: 'active',
      color: 'Reddish-brown to black',
      image_url: '/images/ores/iron-ore.jpg'
    },
    {
      id: 'O-0006',
      name: 'Chromite Ore',
      rock_code: 'O-0006',
      commodity_type: 'Chromium',
      ore_group: 'Magmatic',
      mining_company: 'Krominco Inc.',
      type: 'Podiform Chromite',
      hardness: '5.5-6',
      category: 'Ore Samples',
      locality: 'Homonhon Island, Eastern Samar',
      description: 'Massive Chromite with Serpentinite',
      latitude: '10° 44\' 24" N',
      longitude: '125° 42\' 30" E',
      status: 'active',
      color: 'Black with metallic luster',
      image_url: '/images/ores/chromite-ore.jpg'
    },
    {
      id: 'O-0007',
      name: 'Lead-Zinc Ore',
      rock_code: 'O-0007',
      commodity_type: 'Lead-Zinc',
      ore_group: 'Hydrothermal (MVT)',
      mining_company: 'Philex Mining Corporation',
      type: 'Mississippi Valley-Type Ore',
      hardness: '2.5-3',
      category: 'Ore Samples',
      locality: 'Tuba, Benguet',
      description: 'Galena and Sphalerite in Dolomitic Host Rock',
      latitude: '16° 19\' 48" N',
      longitude: '120° 36\' 36" E',
      status: 'active',
      color: 'Silver-gray to dark brown',
      image_url: '/images/ores/lead-zinc-ore.jpg'
    }
  ];
  
  // Return only rocks of the requested category
  return mockData.filter(rock => rock.category === category);
};

export function useReadRocks(category: string | RockCategory) {
  return useQuery({
    queryKey: [Q_KEYS.ROCKS, category],
    queryFn: () => getRocks(category),
    staleTime: 1000 * 60 * 5, // 5 minutes
  });
} 